PUT http://localhost:3000/users/edit

###
GET http://localhost:3000/products

###
PUT http://localhost:3000/products

###
POST http://localhost:3000/products

###
DELETE http://localhost:3000/products

###
GET http://localhost:3000/users/view/8129