POST http://localhost:3000/api/users/register
Content-Type: application/json

{ 
    "username": "Diego",
    "email": "diego@codehouse.com",
    "password": "12345"
}


###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "diego@codehouse.com",
    "password": "12345"
}

